site_name: Shiru ka
site_url: http://www.shiruka.net
site_description: Shir uka Documentation.
site_author: Shiru ka

repo_url: https://github.com/shiruka/docs.shiruka.net

theme:
  name: 'readthedocs'
  features:
    - toc.integrate

plugins:
  - search
  - awesome-pages
  - i18n:
      languages:
        tr: "Turkish"
        en: "English"
      default_language: 'en'
